In [1]:
import pandas as pd

In [2]:
# Define the path to your directory containing Excel files
# You can use a wildcard '*' to match all Excel files (.xlsx or .xls): 
# 
csv_files_path = "C:/Users/ukhan/Documents/DataSet/OpenMesh/nceia_noaa/"

In [3]:
# Define the path to your directory containing Excel files
# You can use a wildcard '*' to match all Excel files (.xlsx or .xls): 
# 
open_mesh_path = "C:/Users/ukhan/Documents/DataSet/OpenMesh/"

### Merge Open Mesh data with weather data

In [6]:
weather_data = pd.read_csv(csv_files_path+'2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_chkpoint2.csv')

In [5]:
weather_data = pd.read_csv(csv_files_path+'2023_2024_lat_40_6__40_8__lon_-74_01__-73_92_nyc_44K_chkpoint2_22cols.csv')

In [6]:
weather_data.shape

(11448, 19)

In [7]:
open_mesh_data = pd.read_csv(open_mesh_path+"wireless_data_merged_nearest_coord_1.csv")

In [8]:
open_mesh_data.columns

Index(['Datetime', 'sublink_id', 'rsl_value', 'frequency', 'length', 'rsl',
       'nr_site_0_lat', 'nr_site_0_lon'],
      dtype='object')

In [9]:
open_mesh_data.shape

(32452469, 8)

In [10]:
open_mesh_data.head()

,Datetime,sublink_id,rsl_value,frequency,length,rsl,nr_site_0_lat,nr_site_0_lon
0,2023-10-29 00:00:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
1,2023-10-29 00:01:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
2,2023-10-29 00:02:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
3,2023-10-29 00:03:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925
4,2023-10-29 00:04:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925

In [11]:
open_mesh_data['Datetime'] = pd.to_datetime(open_mesh_data.Datetime)

In [12]:
open_mesh_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32452469 entries, 0 to 32452468
Data columns (total 8 columns):
 #   Column         Dtype
---  ------         -----
 0   Datetime       datetime64[ns]
 1   sublink_id     int64
 2   rsl_value      float64
 3   frequency      int64
 4   length         float64
 5   rsl            float64
 6   nr_site_0_lat  float64
 7   nr_site_0_lon  float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 1.9 GB

In [13]:
weather_data.head()

,DATE,LATITUDE,LONGITUDE,ELEVATION,WND_SPEED_MPS,WND_TYPE_CODE_N,WND_TYPE_CODE_V,CIG_AGL,VIS_DISTANCE_MTS,TMP_C,DEW_TMP_C,SLP_HECTOPASCALS,GD1_HEIGHT_MTS,GD1__1,GD1__2,GD1__3,GD1__4,GD1__5,MA1_ALTIMETER_HECTOPASCAL
0,2023-10-29 00:56:00,40.701214,-74.009028,2.13,0,0,0,1829,16093,228,156,10176,1829.0,0,0,0,1,0,10176.0
1,2023-10-29 01:56:00,40.701214,-74.009028,2.13,21,0,1,22000,16093,211,133,10183,1981.0,1,0,0,0,0,10186.0
2,2023-10-29 02:56:00,40.701214,-74.009028,2.13,0,0,0,22000,16093,200,106,10188,1829.0,1,0,0,0,0,10190.0
3,2023-10-29 03:56:00,40.701214,-74.009028,2.13,26,1,0,22000,16093,189,100,10190,2438.0,1,0,0,0,0,10193.0
4,2023-10-29 04:56:00,40.701214,-74.009028,2.13,21,0,1,2438,16093,178,94,10191,2438.0,0,0,1,0,0,10193.0

In [14]:
weather_data.DATE = pd.to_datetime(weather_data.DATE)

In [15]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11448 entries, 0 to 11447
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   DATE                       11448 non-null  datetime64[ns]
 1   LATITUDE                   11448 non-null  float64
 2   LONGITUDE                  11448 non-null  float64
 3   ELEVATION                  11448 non-null  float64
 4   WND_SPEED_MPS              11448 non-null  int64
 5   WND_TYPE_CODE_N            11448 non-null  int64
 6   WND_TYPE_CODE_V            11448 non-null  int64
 7   CIG_AGL                    11448 non-null  int64
 8   VIS_DISTANCE_MTS           11448 non-null  int64
 9   TMP_C                      11448 non-null  int64
 10  DEW_TMP_C                  11448 non-null  int64
 11  SLP_HECTOPASCALS           11448 non-null  int64
 12  GD1_HEIGHT_MTS             8705 non-null   float64
 13  GD1__1                     11448 non-null  int64
 14  GD1__2                     11448 non-null  int64
 15  GD1__3                     11448 non-null  int64
 16  GD1__4                     11448 non-null  int64
 17  GD1__5                     11448 non-null  int64
 18  MA1_ALTIMETER_HECTOPASCAL  11448 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(13)
memory usage: 1.7 MB

In [16]:
open_mesh_data.columns

Index(['Datetime', 'sublink_id', 'rsl_value', 'frequency', 'length', 'rsl',
       'nr_site_0_lat', 'nr_site_0_lon'],
      dtype='object')

In [17]:
weather_data.columns

Index(['DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'WND_SPEED_MPS',
       'WND_TYPE_CODE_N', 'WND_TYPE_CODE_V', 'CIG_AGL', 'VIS_DISTANCE_MTS',
       'TMP_C', 'DEW_TMP_C', 'SLP_HECTOPASCALS', 'GD1_HEIGHT_MTS', 'GD1__1',
       'GD1__2', 'GD1__3', 'GD1__4', 'GD1__5', 'MA1_ALTIMETER_HECTOPASCAL'],
      dtype='object')

### Merge weather data and wireless data on DATE and lat column

* Inner Join to drop columns for which match is not found

In [18]:
wireless_weather_data_df = pd.merge(open_mesh_data, weather_data, left_on=['Datetime', 'nr_site_0_lat'], right_on=['DATE', 'LATITUDE'], how='inner')

In [19]:
wireless_weather_data_df.shape

(581376, 27)

In [20]:
weather_data.shape

(11448, 19)

In [21]:
open_mesh_data.shape

(32452469, 8)

In [22]:
wireless_weather_data_df.to_csv(open_mesh_path+"wireless_weather_data_638K.csv", index=False)

In [23]:
wireless_weather_data_df.head()

,Datetime,sublink_id,rsl_value,frequency,length,rsl,nr_site_0_lat,nr_site_0_lon,DATE,LATITUDE,...,TMP_C,DEW_TMP_C,SLP_HECTOPASCALS,GD1_HEIGHT_MTS,GD1__1,GD1__2,GD1__3,GD1__4,GD1__5,MA1_ALTIMETER_HECTOPASCAL
0,2023-10-29 00:51:00,1,-65.0,62640,623.0,-60.0,40.77898,-73.96925,2023-10-29 00:51:00,40.77898,...,222,144,10176,1829.0,0,0,1,0,0,10186.0
1,2023-10-29 00:51:00,2,-59.0,60480,222.1,-62.0,40.77898,-73.96925,2023-10-29 00:51:00,40.77898,...,222,144,10176,1829.0,0,0,1,0,0,10186.0
2,2023-10-29 00:51:00,3,-61.0,62640,623.0,-60.0,40.77898,-73.96925,2023-10-29 00:51:00,40.77898,...,222,144,10176,1829.0,0,0,1,0,0,10186.0
3,2023-10-29 00:51:00,4,-56.0,58320,451.8,-57.0,40.77898,-73.96925,2023-10-29 00:51:00,40.77898,...,222,144,10176,1829.0,0,0,1,0,0,10186.0
4,2023-10-29 00:51:00,5,-58.0,60480,222.1,-57.0,40.77898,-73.96925,2023-10-29 00:51:00,40.77898,...,222,144,10176,1829.0,0,0,1,0,0,10186.0